'use strict';

/**
 * PDF export route.
 *
 * GET /api/pdf/export?id=<article-slug>
 *
 * Returns a binary PDF generated by headless Chrome (Puppeteer).
 * No browser chrome, no URL bar, no date/page-number headers — a clean,
 * branded document indistinguishable from a Stripe or Google design note.
 *
 * Public endpoint — articles are public, so their PDFs are too.
 * Rate-limited to 10 requests / 15 min per IP to protect Cloud Run CPU.
 */

const express   = require('express');
const rateLimit = require('express-rate-limit');
const { AppError } = require('../errors');
const { generateArticlePdf } = require('../services/pdf');

const router = express.Router();

const pdfLimiter = rateLimit({
  windowMs:         15 * 60 * 1000,  // 15 minutes
  max:              10,
  standardHeaders:  true,
  legacyHeaders:    false,
  message:          { success: false, code: 'RATE_LIMITED', error: 'Too many PDF exports. Try again in 15 minutes.' },
});

// Quick Chrome health-check — does NOT generate a PDF, just tries to launch
// and immediately close Chrome. Use this to diagnose startup failures on Cloud Run.
router.get('/health', async (_req, res) => {
  try {
    const puppeteer = require('puppeteer-core');
    const { resolveChromePath } = require('../services/pdf');
    const executablePath = resolveChromePath();
    const browser = await puppeteer.launch({
      executablePath,
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
    });
    await browser.close();
    res.json({ ok: true, chrome: executablePath });
  } catch (err) {
    res.status(500).json({ ok: false, error: err.message });
  }
});

router.get('/export', pdfLimiter, async (req, res, next) => {
  try {
    const { id } = req.query;
    if (!id || typeof id !== 'string' || !/^[\w-]+$/.test(id)) {
      return res.status(400).json({ success: false, code: 'BAD_REQUEST', error: 'Missing or invalid article id.' });
    }

    // Derive the base URL from the incoming request so this works on any
    // environment (local, staging, production) without env vars.
    const proto   = req.headers['x-forwarded-proto'] || req.protocol;
    const host    = req.headers['x-forwarded-host']  || req.get('host');
    const baseUrl = `${proto}://${host}`;

    const pdfBuffer = await generateArticlePdf(id, baseUrl);

    // Use a human-readable filename so the download dialog shows it correctly,
    // e.g. "salesforce-mulesoft-authentication-system-design.pdf"
    const filename = `${id}-system-design.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.send(pdfBuffer);
  } catch (err) {
    // Surface the real Puppeteer/Chrome error so we can diagnose it.
    // Wrap as operational so errorHandler forwards the message to the client.
    next(new AppError('PDF generation failed: ' + err.message, 500, 'PDF_ERROR'));
  }
});

module.exports = router;
