'use strict';

/**
 * PDF export route.
 *
 * GET /api/pdf/export?id=<article-slug>
 *
 * Returns a binary PDF generated by headless Chrome (Puppeteer).
 * No browser chrome, no URL bar, no date/page-number headers — a clean,
 * branded document indistinguishable from a Stripe or Google design note.
 *
 * Rate-limited to 10 requests / 15 min per IP to protect Cloud Run CPU.
 */

const express     = require('express');
const rateLimit   = require('express-rate-limit');
const { requireAdmin } = require('../middleware/auth');
const { generateArticlePdf } = require('../services/pdf');

const router = express.Router();

const pdfLimiter = rateLimit({
  windowMs:         15 * 60 * 1000,  // 15 minutes
  max:              10,
  standardHeaders:  true,
  legacyHeaders:    false,
  message:          { success: false, code: 'RATE_LIMITED', error: 'Too many PDF exports. Try again in 15 minutes.' },
});

router.get('/export', pdfLimiter, requireAdmin, async (req, res, next) => {
  try {
    const { id } = req.query;
    if (!id || typeof id !== 'string' || !/^[\w-]+$/.test(id)) {
      return res.status(400).json({ success: false, code: 'BAD_REQUEST', error: 'Missing or invalid article id.' });
    }

    // Derive the base URL from the incoming request so this works on any
    // environment (local, staging, production) without env vars.
    const proto   = req.headers['x-forwarded-proto'] || req.protocol;
    const host    = req.headers['x-forwarded-host']  || req.get('host');
    const baseUrl = `${proto}://${host}`;

    const pdfBuffer = await generateArticlePdf(id, baseUrl);

    // Use a human-readable filename so the download dialog shows it correctly,
    // e.g. "salesforce-mulesoft-authentication-system-design.pdf"
    const filename = `${id}-system-design.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.send(pdfBuffer);
  } catch (err) {
    next(err);
  }
});

module.exports = router;
